- name: GitHub Project Board Automation
  # You may pin to the exact commit or the version.
  # uses: pritishvaidya/github-project-board-automation@2583d56fa67eb814a7f8b11c02a52e34a05c6046
  uses: pritishvaidya/github-project-board-automation@0.0.1.9
  with:
    # The GITHUB_TOKEN secret can be passed in using {{ secrets.GITHUB_TOKEN }}
    token: 
    # Comma separated values of Project Board
    projects: 
    # The name of the column in the Github project board to perform an action
    column: 
    # The type of action to be performed. Can be one of `update`, `archive` or `remove`.

    action: # optional, default is update

